// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Element struct {
	ID        uuid.UUID
	Satnum    int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Epoch     time.Time
	Line1     string
	Line2     string
}

type Satellite struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transient struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Expstart  time.Time
	Exptime   float64
	Ra1       float64
	Ra2       float64
	Dec1      float64
	Dec2      float64
	Satnum    sql.NullInt32
	Imgdata   string
}
