// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Transient struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Expstart  time.Time
	Exptime   float64
	Ra1       float64
	Ra2       float64
	Dec1      float64
	Dec2      float64
}
