// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: satellite.sql

package database

import (
	"context"
)

const getSatellite = `-- name: GetSatellite :one
SELECT id, name, created_at, updated_at, epoch, line1, line2 from satellites
	WHERE id = $1
`

func (q *Queries) GetSatellite(ctx context.Context, id int32) (Satellite, error) {
	row := q.db.QueryRowContext(ctx, getSatellite, id)
	var i Satellite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Epoch,
		&i.Line1,
		&i.Line2,
	)
	return i, err
}

const resetSatellites = `-- name: ResetSatellites :exec
DELETE FROM satellites
`

func (q *Queries) ResetSatellites(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSatellites)
	return err
}
