// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transient.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTransient = `-- name: CreateTransient :one
INSERT INTO transients (id, created_at, updated_at, expstart, exptime, ra1, ra2, dec1, dec2, satnum, imgdata)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8
)
RETURNING id, created_at, updated_at, expstart, exptime, ra1, ra2, dec1, dec2, satnum, imgdata
`

type CreateTransientParams struct {
	Expstart time.Time
	Exptime  float64
	Ra1      float64
	Ra2      float64
	Dec1     float64
	Dec2     float64
	Satnum   sql.NullInt32
	Imgdata  string
}

func (q *Queries) CreateTransient(ctx context.Context, arg CreateTransientParams) (Transient, error) {
	row := q.db.QueryRowContext(ctx, createTransient,
		arg.Expstart,
		arg.Exptime,
		arg.Ra1,
		arg.Ra2,
		arg.Dec1,
		arg.Dec2,
		arg.Satnum,
		arg.Imgdata,
	)
	var i Transient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expstart,
		&i.Exptime,
		&i.Ra1,
		&i.Ra2,
		&i.Dec1,
		&i.Dec2,
		&i.Satnum,
		&i.Imgdata,
	)
	return i, err
}

const getSomeTransients = `-- name: GetSomeTransients :many
SELECT id, created_at, updated_at, expstart, exptime, ra1, ra2, dec1, dec2, satnum, imgdata from transients
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetSomeTransients(ctx context.Context, limit int32) ([]Transient, error) {
	rows, err := q.db.QueryContext(ctx, getSomeTransients, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transient
	for rows.Next() {
		var i Transient
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Expstart,
			&i.Exptime,
			&i.Ra1,
			&i.Ra2,
			&i.Dec1,
			&i.Dec2,
			&i.Satnum,
			&i.Imgdata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransient = `-- name: GetTransient :one
SELECT id, created_at, updated_at, expstart, exptime, ra1, ra2, dec1, dec2, satnum, imgdata from transients
	WHERE id = $1
`

func (q *Queries) GetTransient(ctx context.Context, id uuid.UUID) (Transient, error) {
	row := q.db.QueryRowContext(ctx, getTransient, id)
	var i Transient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expstart,
		&i.Exptime,
		&i.Ra1,
		&i.Ra2,
		&i.Dec1,
		&i.Dec2,
		&i.Satnum,
		&i.Imgdata,
	)
	return i, err
}

const getTransientsOfSatellite = `-- name: GetTransientsOfSatellite :many
SELECT id, created_at, updated_at, expstart, exptime, ra1, ra2, dec1, dec2, satnum, imgdata from transients
	WHERE satnum = $1
`

func (q *Queries) GetTransientsOfSatellite(ctx context.Context, satnum sql.NullInt32) ([]Transient, error) {
	rows, err := q.db.QueryContext(ctx, getTransientsOfSatellite, satnum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transient
	for rows.Next() {
		var i Transient
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Expstart,
			&i.Exptime,
			&i.Ra1,
			&i.Ra2,
			&i.Dec1,
			&i.Dec2,
			&i.Satnum,
			&i.Imgdata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniqueTransients = `-- name: GetUniqueTransients :many
SELECT satnum from transients
GROUP BY satnum
`

func (q *Queries) GetUniqueTransients(ctx context.Context) ([]sql.NullInt32, error) {
	rows, err := q.db.QueryContext(ctx, getUniqueTransients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var satnum sql.NullInt32
		if err := rows.Scan(&satnum); err != nil {
			return nil, err
		}
		items = append(items, satnum)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reset = `-- name: Reset :exec
DELETE FROM transients
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
